<a href="https://colab.research.google.com/github/Dih08/projetos-simples-e-aleatorios/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
previsores = iris.data
classe = iris.target
previsores[0:4,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [6]:
#padronizados
sc = StandardScaler()
previsores = sc.fit_transform(previsores)
previsores[0:4,:]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ]])

In [7]:
Xtrain, Xtest, ytrain, ytest = train_test_split(previsores, classe, test_size = 0.3, random_state = 1234)

In [8]:
floresta = RandomForestClassifier(n_estimators = 100,random_state=1234)
floresta.fit(Xtrain, ytrain)
previsoes = floresta.predict(Xtest)
confusao = confusion_matrix(ytest, previsoes)
taxa_acerto = accuracy_score(ytest, previsoes)

In [9]:
taxa_acerto

0.9555555555555556

In [10]:
#previsores ja padronizados
#redução de dimensionalidade
pca = PCA(n_components=3)
previsores_pca = pca.fit_transform(previsores)
previsores_pca[0:4,:]

array([[-2.26470281,  0.4800266 , -0.12770602],
       [-2.08096115, -0.67413356, -0.23460885],
       [-2.36422905, -0.34190802,  0.04420148],
       [-2.29938422, -0.59739451,  0.09129011]])

In [11]:
Xtrain, Xtest, ytrain, ytest = train_test_split(previsores_pca, classe, test_size = 0.3, random_state = 1234)

In [12]:
floresta = RandomForestClassifier(n_estimators = 100,random_state=1234)
floresta.fit(Xtrain, ytrain)
previsoes = floresta.predict(Xtest)
confusao = confusion_matrix(ytest, previsoes)
taxa_acerto = accuracy_score(ytest, previsoes)

In [13]:
taxa_acerto

0.9333333333333333