<a href="https://colab.research.google.com/github/Dih08/projetos-simples-e-aleatorios/blob/main/Q_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#bibliotecas

import numpy as np
import pandas as pd

In [2]:
#definindo estado e ações a sera, tomadas

states = [0,1,2,3,4,5]
actions = [0,1,2,3,4,5]

#parametro gamma

gamma = 0.8
goal_state = 5


In [3]:
#matriz de recompensa
R = [[-1,-1,-1,-1,0,-1],
     [-1,-1,-1,0,-1,100],
     [-1,-1,-1,0,-1,-1],
     [-1,0,0,-1,0,-1],
     [0,-1,-1,0,-1,100],
     [-1,0,-1,-1,0,100]]

R = np.array(R)
print('Matriz de recompensa')
print(pd.DataFrame(R, index=['state_'+str(i) for i in range(R.shape[0])],
                   columns=['state_' +str(i) for i in range(R.shape[0])],))


Matriz de recompensa
         state_0  state_1  state_2  state_3  state_4  state_5
state_0       -1       -1       -1       -1        0       -1
state_1       -1       -1       -1        0       -1      100
state_2       -1       -1       -1        0       -1       -1
state_3       -1        0        0       -1        0       -1
state_4        0       -1       -1        0       -1      100
state_5       -1        0       -1       -1        0      100


In [5]:
#Inicializando a matriz 0 -zerada
Q = np.zeros((len(states), len(actions)))
print('Q-matrix')
print(pd.DataFrame(Q, index=['state_'+str(i) for i in range(Q.shape[0])],
                   columns=['state_' +str(i) for i in range(Q.shape[0])],))

Q-matrix
         state_0  state_1  state_2  state_3  state_4  state_5
state_0      0.0      0.0      0.0      0.0      0.0      0.0
state_1      0.0      0.0      0.0      0.0      0.0      0.0
state_2      0.0      0.0      0.0      0.0      0.0      0.0
state_3      0.0      0.0      0.0      0.0      0.0      0.0
state_4      0.0      0.0      0.0      0.0      0.0      0.0
state_5      0.0      0.0      0.0      0.0      0.0      0.0


In [9]:
#função auxiliar
def get_possible_next_state(R,state):
  possible_next_states = np.argwhere(R[state,: ] >= 0).reshape(-1,)
  return possible_next_states

In [10]:
#examplos
get_possible_next_state(R, state = 0)

array([4])

In [11]:
get_possible_next_state(R, state = 3)

array([1, 2, 4])

In [12]:
#construindo um episódio


#escolhendo o estado
state = np.random.choice(states, size = 1)[0]

#looping while
next_state = None
while next_state != goal_state:

#escolhendo os proximos estados
   possible_next_states = get_possible_next_state(R, state)

#Definimos o proximo estado
   next_state = np.random.choice(possible_next_states, size = 1)[0]
   print('estad0 --> proximo estado ',state,next_state)

#  Atuslizando de acordo com as decisões tomadas
   M = Q[next_state, get_possible_next_state(R, next_state)].max()
   Q[state, next_state] = R[state, next_state] + gamma * M

   state = next_state
   print()

print('fim')
print()
print('q-matrix atualizado')
print(Q)

estad0 --> proximo estado  0 4

estad0 --> proximo estado  4 3

estad0 --> proximo estado  3 2

estad0 --> proximo estado  2 3

estad0 --> proximo estado  3 2

estad0 --> proximo estado  2 3

estad0 --> proximo estado  3 1

estad0 --> proximo estado  1 3

estad0 --> proximo estado  3 4

estad0 --> proximo estado  4 0

estad0 --> proximo estado  0 4

estad0 --> proximo estado  4 5

fim

q-matrix atualizado
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]]


In [13]:
# rodando um segundo episodio


#escolhendo o estado
state = np.random.choice(states, size = 1)[0]

#looping while
next_state = None
while next_state != goal_state:

#escolhendo os proximos estados
   possible_next_states = get_possible_next_state(R, state)

#Definimos o proximo estado
   next_state = np.random.choice(possible_next_states, size = 1)[0]
   print('estad0 --> proximo estado ',state,next_state)

#  Atuslizando de acordo com as decisões tomadas
   M = Q[next_state, get_possible_next_state(R, next_state)].max()
   Q[state, next_state] = R[state, next_state] + gamma * M

   state = next_state
   print()

print('fim')
print()
print('q-matrix atualizado')
print(Q)

estad0 --> proximo estado  3 1

estad0 --> proximo estado  1 5

fim

q-matrix atualizado
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]]


In [14]:
# terceiro episodio

#construindo um episódio


#escolhendo o estado
state = np.random.choice(states, size = 1)[0]

#looping while
next_state = None
while next_state != goal_state:

#escolhendo os proximos estados
   possible_next_states = get_possible_next_state(R, state)

#Definimos o proximo estado
   next_state = np.random.choice(possible_next_states, size = 1)[0]
   print('estad0 --> proximo estado ',state,next_state)

#  Atuslizando de acordo com as decisões tomadas
   M = Q[next_state, get_possible_next_state(R, next_state)].max()
   Q[state, next_state] = R[state, next_state] + gamma * M

   state = next_state
   print()

print('fim')
print()
print('q-matrix atualizado')
print(Q)

estad0 --> proximo estado  0 4

estad0 --> proximo estado  4 3

estad0 --> proximo estado  3 2

estad0 --> proximo estado  2 3

estad0 --> proximo estado  3 4

estad0 --> proximo estado  4 0

estad0 --> proximo estado  0 4

estad0 --> proximo estado  4 0

estad0 --> proximo estado  0 4

estad0 --> proximo estado  4 5

fim

q-matrix atualizado
[[  0.   0.   0.   0.  80.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  80.   0.]
 [ 64.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]]


In [15]:
#quarto episodio

#construindo um episódio


#escolhendo o estado
state = np.random.choice(states, size = 1)[0]

#looping while
next_state = None
while next_state != goal_state:

#escolhendo os proximos estados
   possible_next_states = get_possible_next_state(R, state)

#Definimos o proximo estado
   next_state = np.random.choice(possible_next_states, size = 1)[0]
   print('estad0 --> proximo estado ',state,next_state)

#  Atuslizando de acordo com as decisões tomadas
   M = Q[next_state, get_possible_next_state(R, next_state)].max()
   Q[state, next_state] = R[state, next_state] + gamma * M

   state = next_state
   print()

print('fim')
print()
print('q-matrix atualizado')
print(Q)

estad0 --> proximo estado  0 4

estad0 --> proximo estado  4 0

estad0 --> proximo estado  0 4

estad0 --> proximo estado  4 3

estad0 --> proximo estado  3 1

estad0 --> proximo estado  1 3

estad0 --> proximo estado  3 4

estad0 --> proximo estado  4 0

estad0 --> proximo estado  0 4

estad0 --> proximo estado  4 5

fim

q-matrix atualizado
[[  0.   0.   0.   0.  80.   0.]
 [  0.   0.   0.  64.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  80.   0.   0.  80.   0.]
 [ 64.   0.   0.  64.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]]


In [16]:
#quinto episodio

#construindo um episódio


#escolhendo o estado
state = np.random.choice(states, size = 1)[0]

#looping while
next_state = None
while next_state != goal_state:

#escolhendo os proximos estados
   possible_next_states = get_possible_next_state(R, state)

#Definimos o proximo estado
   next_state = np.random.choice(possible_next_states, size = 1)[0]
   print('estad0 --> proximo estado ',state,next_state)

#  Atuslizando de acordo com as decisões tomadas
   M = Q[next_state, get_possible_next_state(R, next_state)].max()
   Q[state, next_state] = R[state, next_state] + gamma * M

   state = next_state
   print()

print('fim')
print()
print('q-matrix atualizado')
print(Q)

estad0 --> proximo estado  5 4

estad0 --> proximo estado  4 5

fim

q-matrix atualizado
[[  0.   0.   0.   0.  80.   0.]
 [  0.   0.   0.  64.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  80.   0.   0.  80.   0.]
 [ 64.   0.   0.  64.   0. 164.]
 [  0.   0.   0.   0.  80.   0.]]


In [28]:
class Q_learning:

  def __init__(self, states, actions,R, gamma, goal_state):
    self.states = states
    self.actions = actions
    self.R = R
    self.gamma = gamma
    self.goal_state = goal_state
    self.Q = np.zeros(len(states)* len(actions)).reshape(len(states), len(actions))
    self.Q = Q

  def get_Qmatrix(self):
    Qdf = pd.DataFrame(self.Q, index=['state_'+str(i) for i in range(self.Q.shape[0])],
                   columns=['action_' +str(i) for i in range(self.Q.shape[1])]).astype(int)
    return Qdf

  def run_episode(self):
      state = np.random.choice(self.states, size = 1)[0]
      next_state = None
      while next_state != self.goal_state:
         possible_next_states = get_possible_next_state(R, state)
         next_state = np.random.choice(possible_next_states, size = 1)[0]
         M = self.Q[next_state, get_possible_next_state(R, next_state)].max()
         self.Q[state, next_state] = self.R[state, next_state] + self.gamma * M
         state = next_state

  def train_agent(self, n_episodes):
     for e in range(n_episodes):
       self.run_episode()

In [29]:
#instanciando um agente
agente = Q_learning(states=states,
                   actions=actions,
                   R=R,
                   gamma=gamma,
                   goal_state=goal_state)

In [32]:
agente.get_Qmatrix()

action_0  action_1  action_2  action_3  action_4  action_5
state_0         0         0         0         0        80         0
state_1         0         0         0        64         0       100
state_2         0         0         0         0         0         0
state_3         0        80         0         0        80         0
state_4        64         0         0        64         0       164
state_5         0         0         0         0        80         0

In [34]:
agente.train_agent(n_episodes=10)
agente.get_Qmatrix()


action_0  action_1  action_2  action_3  action_4  action_5
state_0         0         0         0         0       399         0
state_1         0         0         0       319         0       499
state_2         0         0         0       319         0         0
state_3         0       399       255         0       399         0
state_4       319         0         0       319         0       499
state_5         0       399         0         0       399       499